include/uapi/asm-generic/signal.h: use __kernel_size_t instead of size_t
Fixes userspace compiler error:

error: unknown type name ‘size_t’

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>