include/uapi/linux/kexec.h: use __kernel_size_t instead of size_t
Fixes userspace compilation error:

error: unknown type name ‘size_t’
  size_t bufsz;

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>