uapi linux/fsmap.h: use __kernel_size_t instead of size_t
Fixes user space compilation error:

linux/fsmap.h:71:19: error: unknown type name ‘size_t’
 static __inline__ size_t
                   ^~~~~~

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
Cc: Darrick J. Wong <darrick.wong@oracle.com>