arch/x86/include/uapi/asm/signal.h: use __kernel_size_t instead of size_t
Fixes userspace compilation error:

error: unknown type name ‘size_t’

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>