include/uapi/sound/emu10k1.h: added EMU10K1 version of DECLARE_BITMAP etc macros
Fixes userspace compilation error:

error: expected specifier-qualifier-list before ‘DECLARE_BITMAP’
  DECLARE_BITMAP(gpr_valid, 0x200); /* bitmask of valid initializers */

DECLARE_BITMAP etc macros are not meant for userspace headers and thus
added here as private copies for emu10k.h.

Fix was suggested by Arnd Bergmann <arnd@arndb.de> in message
<2168807.4Yxh5gl11Q@wuerfel> on lkml.

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>