uapi xen/gntdev.h: include xen/privcmd.h and define grant_ref_t
Both are needed to compile <xen/gntdev.h> in userspace. Fixes these
userspace compile errors:

xen/gntdev.h:151:4: error: unknown type name ‘grant_ref_t’
    grant_ref_t ref;
    ^
xen/gntdev.h:153:4: error: unknown type name ‘domid_t’
    domid_t domid;
    ^

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
Cc: Boris Ostrovsky <boris.ostrovsky@oracle.com>
Cc: Juergen Gross <jgross@suse.com>
Cc: xen-devel@lists.xenproject.org