include/uapi/xen/privcmd.h: fix compilation in userspace
xen/interface/xen.h is not exported from kernel headers so remove the
dependency and provide needed defines for domid_t and xen_pfn_t if they
are not already defined by some other e.g. Xen specific headers.

Suggested by Andrew Cooper <andrew.cooper3@citrix.com> on lkml message
<5569F9C9.8000607@citrix.com>.

Use <linux/types.h> based defition for xen_pfn_t so that both uapi and
kernel side headers are compatible.

The ifdef for ARM is ugly but did not find better solutions for it now.

Fixes userspace compilation error:

xen/privcmd.h:38:31: fatal error: xen/interface/xen.h: No such file or directory

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>