include/uapi/sound/Kbuild: remove sound/asoc.h from userspace
Based on git commit messages and the #error macro messages it should not be
used in userspace. Fixes userspace compile errors:

sound/asoc.h:21:2: error: #error This API is an early revision and not enabled
 in the current
 #error This API is an early revision and not enabled in the current
  ^~~~~
sound/asoc.h:22:2: error: #error kernel release, it will be enabled in a futur
e kernel version
 #error kernel release, it will be enabled in a future kernel version
  ^~~~~
sound/asoc.h:23:2: error: #error with incompatible changes to what is here.
 #error with incompatible changes to what is here.
  ^~~~~

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>