uapi linux/reiserfs_xattr.h: use __kernel_size_t instead of size_t
Fixes userspace compilation error:

error: unknown type name ‘size_t’
  size_t length;

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
Cc: reiserfs-devel@vger.kernel.org