HACK include/uapi/linux/elfcore.h: use __kernel_pid_t and remove elf_greg_t stuff in userspace
__kernel_pid_t change feels like right one. Commenting out elf_greg_t
things in userspace does not but exporting x86/include/asm/elf.h and its
dependencies to userspace does not feel right either. Hence HACK.

Fixes userspace compilation errors like:

error: unknown type name ‘elf_greg_t’
 typedef elf_greg_t greg_t;
error: unknown type name ‘pid_t’
  pid_t pr_pid;

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>